### PR TITLE
Add osx description to Readme file

### PR DESCRIPTION
**Pull request by bonsak**

### CODE REVIEW

**Comment by gadfly16** [comment]
Thanks! Would you add an explanatory line before the section? Are the `exports` mandatory? Is it mandatory to leave the spaces out? None of us currently uses OSX for work so we can not test these.

Thanks again!

**Comment by bonsak** [comment]
Sorry about that :)
https://github.com/bonsak/qLib/commit/3efb3b662d950b8f67ed8edc9651ce1774b78147

**Comment by johnnyquest** [comment]
looks more or less the linux version... maybe we should get rid of the spaces in the linux version, and say "linux/OSX"? @gadfly16 ? what do you guys think?

**Comment by bonsak** [comment]
Osx and Linux are the same. I just copied this from the online help:
> Linux
> On Linux, the procedure for setting environment variables varies from shell to shell. Check your shell’s man page for details.

> In bash use export name=value .
> In csh and tcsh, use setenv name value

It seems you can do fine without the spaces for bash on linux as well.

**Comment by johnnyquest** [comment]
ok, apart from the comment typo i'm okay with the merge (but i don't know about OSX anyway :)) unfortunately these days I'm beyond firewalls mostly, @gadfly16 you there? :)

**Comment by bonsak** [comment]
Ops. Sorry :) Fixed now.

**Pull request merged**
