### PR TITLE
fix is_platform on macOS

### PR DESCRIPTION
**Pull request by coolzilj**

### CODE REVIEW

**Comment by johnnyquest** [comment]
Hey -- thanks for the merge request, but I don't think that would work on windows.

Can you try if this works on mac?

```
def is_platform(name):
    assert type(name) is str
    return sys.platform.lower().startswith(name.lower())

def is_linux():
    return is_platform('linux')

def is_windows():
    return is_platform('win')

def is_mac():
    return is_platform('darwin')
```

**Comment by coolzilj** [comment]
Yes, it works well. :)

**Comment by johnnyquest** [comment]
@coolzilj cool, I'll go with this then (according to the python docs, this is the "recommended" way of checking it). I'll check on windows too, at some point... Thanks for the commit and the checking! (I don't have access to a mac so I had no way to test)

**Comment by coolzilj** [comment]
@johnnyquest Haven't tested my modification on Windows either, there's no PC around. :)

Nice work BTW, for such a big lib. 
I'm new to Houdini(mostly doing web dev before), found out that some codes make me confusing, for example, I can't find any informations about `$HIH` enviroment in houdini docs as well as on google and echo nothing in Textport Windows(Houdini 18).
And I found nothing but an index page in help docs. At one time I thought this lib is unmaintained.

**Comment by johnnyquest** [comment]
@coolzilj Thanks! The library is actively maintained. The help docs is a work in progress (e.g. see https://github.com/qLab/qLib/issues/950 -- actually I only started working on it a few days ago) but all nodes (should) have help cards.

Not sure how to get info about variables like `$HIH`, though...

**Pull request closed without merging**
